### ISSUE TITLE
프로그래머스 LEVEL1

### ISSUE THREAD

**Issue by tezla-lee** [ai-creatv/algorithm_jbd1#1]
# [프로그래머스 LEVEL 1](https://github.com/Tezla-Lee/Algorithm/tree/master/FastCampus/src/level1)

**Comment by ai-creatv** [comment]
깔끔하게 잘 구현해서 레벨1을 잘 획득해 주셨네요! :)

- gcd의 경우 빠르게 구현하려면 유클리드 호제법을 쓰면 좋습니다. 한번 찾아보세요!
- List를 거치지 않고 Array만으로도 해결이 가능하니, 그렇게 해보시기 바랍니다. ArrayList에 값을 하나씩 추가하는 과정이 비효율적이네요(내부 Array의 크기를 여러번 증가시켜야 함) :)

수고하셨습니다.
