### ISSUE TITLE
Homework #2

### ISSUE THREAD

**Issue by FoeverNa** [ai-creatv/algorithm_jbd1#10]
[homework#2](https://github.com/FoeverNa/JBS-Algorithm/blob/master/AlgorithmProgrammers/src/datastructure/DoublyLinkedList.java)

**Comment by ai-creatv** [comment]
수고하셨습니다!

다만 테스트코드를 실행해보면 값이 맞지 않네요 ㅠ_ㅠ

access 사용시에 head를 변경하는 부분이 들어갔기 때문으로 보입니다.

해당 코드를 삭제하면 잘 동작하는 것으로 보이네요. 확인 꼭 해주세요 :)
