### ISSUE TITLE
Homework#3 NodeBinaryTreeTest

### ISSUE THREAD

**Issue by LimNoah** [ai-creatv/algorithm_jbd1#11]
[Homework#3 NodeBinaryTreeTest](https://github.com/LimNoah/LNoah-Algorithm/blob/master/FastCampus/src/Homework/Day03/NodeBinaryTreeTest/NodeBinaryTreeTest.java)

**Comment by ai-creatv** [comment]
잘 구현해 주셨습니다! 특히 dfs의 경우 iterative한 방법(스택 활용)까지 같이 해 주셨네요 :) 수고하셨어요!
