### ISSUE TITLE
Homework#3 BinaryTree_NodeBase

### ISSUE THREAD

**Issue by Hansol-Jeong** [ai-creatv/algorithm_jbd1#12]
[@@리컬시브하게@@](https://github.com/Hansol-Jeong/java-til/blob/master/HomeWork/Tree/src/main/java/BinaryTree_NodeBase.java)

Test result:
> Task :BinaryTreeTest_NodeBase.main()
0 1 3 7 8 4 9 2 5 6 
7 3 8 1 9 4 0 5 2 6 
7 3 8 1 9 4 5 2 6 0 
true
false
true
false

**Comment by ai-creatv** [comment]
잘 구현해 주셨습니다! 제가 처음에 기반코드를 잘못 올려뒀는데 잘 수정해서 하셨네요 :) 수고하셨어요!
