### ISSUE TITLE
Homework#3

### ISSUE THREAD

**Issue by FoeverNa** [ai-creatv/algorithm_jbd1#14]
[NodeBinaryTree](https://github.com/FoeverNa/JBS-Algorithm/blob/master/AlgorithmProgrammers/src/datastructure/tree/NodeBinaryTree.java)

**Comment by ai-creatv** [comment]
깔끔한 형태로 잘 구현해 주셨습니다 :) 주변 동료들이 구현한 스택을 활용한 dfs 구현도 알아두시면 좋을 것 같습니다!
