### ISSUE TITLE
Homework #3

### ISSUE THREAD

**Issue by limjoonchul** [ai-creatv/algorithm_jbd1#15]
[노드기반 완전이진트리](https://github.com/limjoonchul/TIL/blob/master/Algorithm/Subject/NodeBinaryTree.md)

**Comment by ai-creatv** [comment]
깔끔하게 잘 구현해 주셨네요 :) bfs의 경우 queue를 시뮬레이션하셨는데, 실제 queue를 사용하시면 좋습니다.

Queue<Node> queue = new LinkedList<>();

위와 같이 링크드리스트 기반의 큐를 구현하여 사용하실 수 있습니다 :)
