### ISSUE TITLE
Homework #1 프로그래머스 Skill Check

### ISSUE THREAD

**Issue by LimNoah** [ai-creatv/algorithm_jbd1#3]
[프로그래머스 Skill Check Level 1](https://github.com/LimNoah/LNoah-Algorithm/tree/master/FastCampus/src/Homework/Day01/ProgrammersLevel1)

**Comment by ai-creatv** [comment]
깔끔하게 잘 구현해서 레벨1을 잘 획득해 주셨네요! :) 수고하셨습니다.
