### ISSUE TITLE
Homework#1 프로그래머스 스킬테스트 레벨1

### ISSUE THREAD

**Issue by FoeverNa** [ai-creatv/algorithm_jbd1#4]
[Homework#1](https://github.com/FoeverNa/JBS-Algorithm/blob/master/homework/SkillCheckLeve1.md)

**Comment by ai-creatv** [comment]
수고많으셨습니다! :)

- 범위 내에서 소수 찾기는, 특정한 방법을 써야 최적화가 가능합니다. 에라토스테네스의 체 라는 방법이 있으니 아래 링크를 참조해 주세요. (https://ko.wikipedia.org/wiki/%EC%97%90%EB%9D%BC%ED%86%A0%EC%8A%A4%ED%85%8C%EB%84%A4%EC%8A%A4%EC%9D%98_%EC%B2%B4)
