### ISSUE TITLE
Homework#2_DoublyLinkedList

### ISSUE THREAD

**Issue by LimNoah** [ai-creatv/algorithm_jbd1#5]
[Homework#2_DoublyLinkedList](https://github.com/LimNoah/LNoah-Algorithm/blob/master/FastCampus/src/Homework/Day02/DoublyLinkedList/DoublyLinkedListTest.java)

**Comment by ai-creatv** [comment]
잘 구현해 주셨습니다! :)

의문으로 남겨두신 null처리 안해도 GC가 될지에 대해서는,

accessNode 변수가 메소드가 종료될떄 스택에서 삭제되기 떄문에 null처리를 한 것과 안한 것이 차이 없이 동일하게 GC가 동작합니다 :)
