### ISSUE TITLE
Homework #2

### ISSUE THREAD

**Issue by tezla-lee** [ai-creatv/algorithm_jbd1#6]
# [DoublyLinkedList](https://github.com/Tezla-Lee/Algorithm/tree/master/FastCampus/src/mydoublylinkedlist)

**Comment by ai-creatv** [comment]
잘 구현해 주셨습니다 :)

다만, prev를 계속 추적하는 부분은 불필요하다는 점 확인을 해주세요!

왜냐하면, curr만 있어도 curr.prev로 prev를 대체할 수 있기 때문입니다 :)
