### ISSUE TITLE
Homework#2 정한솔

### ISSUE THREAD

**Issue by Hansol-Jeong** [ai-creatv/algorithm_jbd1#7]
[DoublyLinkedList와 그에대한 Test](https://github.com/Hansol-Jeong/java-til/tree/master/HomeWork/LinkedList/src).

**Comment by ai-creatv** [comment]
따로 최신버전의 코드로 리뷰를 했기 때문에 여기 코멘트를 달지는 않겠습니다. 수고하셨습니다 👍
