### ISSUE TITLE
Homework #2 

### ISSUE THREAD

**Issue by limjoonchul** [ai-creatv/algorithm_jbd1#8]
[Doubly Linked List](https://github.com/limjoonchul/TIL/blob/master/Algorithm/Subject/DoublyLinkedList.md)

**Comment by ai-creatv** [comment]
cnt 변수를 유지하는 아이디어는 무척 좋습니다! 효율적으로 탐색하는 좋은 아이디어입니다 👍 

그로 인해 평균적으로 2배 빠르게 동작하기 때문에 유용하다고 보여집니다.

수고하셨습니다 :)
