### ISSUE TITLE
Homework #2

### ISSUE THREAD

**Issue by Yus2on** [ai-creatv/algorithm_jbd1#9]
[homework #2](https://github.com/Yus2on/JAVA_TIL/blob/master/Algorithm/5_Homeworks/2/Homework02/src/DLL/DoublyLinkedList.java)

**Comment by ai-creatv** [comment]
잘 구현해 주셨습니다 :) append 등도 tail이 있는 장점을 잘 활용해 주셨네요!

다만 한가지, 탐색을 할 때에 prev를 유지하지 않아도 되는점은 확인해주세요!

이유는, next.prev가 항상 prev와 같기 때문입니다 :)
